openapi: 3.0.0

info:
  version: 1.0.0
  title: MIDISense
  description: "This is the API for the MIDISense System"

tags:
  - name: "Display"
  - name: "Interpreter"
  - name: "Intelligence"

paths:

  #=================================================
  # ENDPOINT DEFINITIONS
  #=================================================

  #============= INTERPRETER ============================

  /interpreter/uploadFile:
    post:
      summary: "Endpoint for the Upload File use case of the Interpreter subsystem"
      tags:
        - "Interpreter"
      description: uploadFile
      operationId: uploadFile
      requestBody:
        description: "Request for uploadFile"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/interpreterUploadFileRequest'
      responses:
        '200':
          description: "Upload File Response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/interpreterUploadFileResponse'

  /interpreter/processFile:
    post:
      summary: "API endpoint to process File"
      tags:
        - "Interpreter"
      description: ProcessFile
      operationId: ProcessFIle
      requestBody:
        description: "Request for processFile"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/interpreterProcessFileRequest'
      responses:
        '200':
          description: "processFile Response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/interpreterProcessFileResponse'

  /interpreter/parseJSON:
    post:
      summary: "Endpoint for parsing an XML of the Interpreter subsystem"
      tags:
        - "Interpreter"
      description: parse to XML file
      operationId: ParseXML
      requestBody:
        description: "Request for parseXML"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/interpreterParseJSONRequest'
      responses:
        '200':
          description: "parseXML Response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/interpreterParseJSONResponse'
        '401':
          description: Invalid File

  /interpreter/parseStaccato:
    post:
      summary: "API endpoint for parsing a file to Staccato"
      tags:
        - "Interpreter"
      description: parseStaccato
      operationId: ParseStaccato
      requestBody:
        description: "Request for parseStaccato"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/interpreterParseStaccatoRequest'
      responses:
        '200':
          description: "parseStaccato Response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/interpreterParseStaccatoResponse'

  /display/getPieceMetadata:
    post:
      summary: "endpoint for getting the piece metadata"
      tags:
        - "Display"
      description: getPieceMetadata
      operationId: getPieceMetadata
      requestBody:
        description: "Request for getPieceMetadata"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/displayGetPieceMetadataRequest'
      responses:
        '200':
          description: "getPieceMetadata Response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/displayGetPieceMetadataResponse'

  /interpreter/interpretMetre:
    post:
      summary: "Endpoint for the Interpret Metre use case of the Interpreter subsystem"
      tags:
        - "Interpreter"
      description: interpretMetre
      operationId: interpretMetre
      requestBody:
        description: "Request for interpretMetre"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/interpreterInterpretMetreRequest'
      responses:
        '200':
          description: "Interpret Metre Response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/interpreterInterpretMetreResponse'

  /interpreter/interpretTempo:
    post:
      summary: "Endpoint for the Interpret Tempo use case of the Interpreter subsystem"
      tags:
        - "Interpreter"
      description: interpretTempo
      operationId: interpretTempo
      requestBody:
        description: "Request for interpretTempo"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/interpreterInterpretTempoRequest'
      responses:
        '200':
          description: "Interpret Tempo Response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/interpreterInterpretTempoResponse'

  /display/getTrackInfo:
    post:
      summary: "Endpoint for receiving the track info"
      tags:
        - "Display"
      description: getTrackInfo
      operationId: getTrackInfo
      requestBody:
        descripiton: "Request for getTrackInfo"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/displayGetTrackInfoRequest'
      responses:
        '200':
          description: "GetTrackInfo Response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/displayGetTrackInfoResponse'

  /display/getTrackMetadata:
    post:
      summary: "Endpoint for receiving the track metadata"
      tags:
        - "Display"
      description: getTrackMetadata
      operationId: getTrackMetadata
      requestBody:
        description: "Request for getTrackMetadata"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/displayGetTrackMetadataRequest'
      responses:
        '200':
          description: "getTrackMetadata Response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/displayGetTrackMetadataResponse'

  /display/getTrackOverview:
    post:
      summary: "Endpoint for getting the track overview"
      tags:
        - "Display"
      description: getTrackOverview
      operationId: getTrackOverview
      requestBody:
        description: "Request for getTrackOverview"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/displayGetTrackOverviewRequest'
      responses:
        '200':
          description: "getTrackOverview response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/displayGetTrackOverviewResponse'

  #=================================================
  # SCHEMAS + OBJECTS
  #=================================================

components:
  schemas:

    interpreterUploadFileRequest:
      description: "Description Here"
      type: object
      properties:
        fileContents:
          type: array
          items:
            type: integer

    interpreterUploadFileResponse:
      type: object
      properties:
        fileDesignator:
          type: string

    interpreterProcessFileRequest:
      description: "Request the ProcessFile"
      type: object
      properties:
        fileDesignator:
          type: string

    interpreterProcessFileResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string


    interpreterParseJSONRequest:
      description: "Description Here"
      type: object
      properties:
        fileContents:
          type: array
          items:
            type: integer

    interpreterParseJSONResponse:
      type: object
      properties:
        fileDesignator:
          type: string

    interpreterParseStaccatoRequest:
      description: "request for parseStaccato"
      type: object
      properties:
        fileContents:
          type: array
          items:
            type: integer

    interpreterParseStaccatoResponse:
      type: object
      properties:
        fileDesignator:
          type: string

    displayGetPieceMetadataRequest:
      type: object
      properties:
        fileDesignator:
          type: string

    displayGetPieceMetadataResponse:
      type: object
      properties:
        tempoIndication:
          type: integer
        keySignature:
          type: string
        timeSignature:
          type: object
          properties:
            numBeats:
              type: integer
            beatValue:
              type: integer

    interpreterInterpretMetreRequest:
      description: "Description Here"
      type: object
      properties:
        fileDesignator:
          type: string

    interpreterInterpretMetreResponse:
      type: object
      properties:
        timeSignature:
          type: object
          properties:
            numBeats:
              type: integer
            beatValue:
              type: integer

    interpreterInterpretTempoRequest:
      description: "Description Here"
      type: object
      properties:
        fileDesignator:
          type: string

    interpreterInterpretTempoResponse:
      type: object
      properties:
        tempoIndication:
          type: integer

    displayGetTrackInfoRequest:
      description: "Request Track Info"
      type: object
      properties:
        fileDesignator:
          type: string

    displayGetTrackInfoResponse:
      type: object
      properties:
        index:
          type: integer
        trackName:
          type: string

    displayGetTrackMetadataRequest:
      description: "Request Track Metadata"
      type: object
      properties:
        fileDesignator:
          type: string
        trackIndex:
          type: integer

    displayGetTrackMetadataResponse:
      type: object
      properties:
        trackString:
          type: String

    displayGetTrackOverviewRequest:
      description: "Request for Track Overview"
      type: object
      properties:
        fileDesignator:
          type: string
        trackIndex:
          type: integer

    displayGetTrackOverviewResponse:
      type: object
      properties:
        pitchArray:
          type: string