openapi: 3.0.0

info:
  version: 1.0.0
  title: MIDISense
  description: "This is the API for the MIDISense System"

tags:
  - name: "Display"
  - name: "Interpreter"
  - name: "Intelligence"

paths:

  /interpreter/parseFile:
    post:
      summary: "Endpoint for the Create Book use case of the Book subsystem"
      tags:
        - "Interpreter"
      description: parseFile
      operationId: parseFile
      requestBody:
        description: "Request for parseFile"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/parseFileRequest'
      responses:
        '200':
          description: "Login response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/parseFileResponse'


components:
  schemas:

    parseFileRequest:
      description: "Description Here"
      type: object
      properties:
        fileContents:
          type: array
          items:
            type: integer

    parseFileResponse:
      type: object
      properties:
        success:
          type: boolean
