swagger: '2.0'

info:
  description: This is the API for the MIDISense System
  version: 1.0.0
  title: MIDISense

host: 'localhost:8080'
basePath: /api

tags:
  - name: display
    description: Display
  - name: interpreter
    description: Interpreter
  - name: intelligence
    description: Intelligence

schemes:
  - https
  - http

paths:
  /display/DisplayMusicMetadata :
    post:
      tags:
        - display
      summary: Returns DisplayMusicMetadata token
      description: DisplayMusicMetadata
      operationId: DisplayMusicMetadata
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: DisplayMusicMetadata Request
          description: Request for DisplayMusicMetadata
          required: true
          schema:
            $ref: '#/definitions/DisplayMusicMetadataRequest'
      responses:
        '200':
          description: Music metadata display response
          schema:
            $ref: '#/definitions/DisplayMusicMetadataResponse'

  /display/DisplayNoteMetadata :
    post:
      tags:
        - display
      summary: Returns DisplayNoteMetadata token
      description: DisplayNoteMetadata
      operationId: DisplayNoteMetadata
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: DisplayNoteMetadata Request
          description: Request for DisplayNoteMetadata
          required: true
          schema:
            $ref: '#/definitions/DisplayNoteMetadataRequest'
      responses:
        '200':
          description: Music metadata display response
          schema:
            $ref: '#/definitions/DisplayNoteMetadataResponse'

definitions:
  DisplayMusicMetadataRequest:
    type: object
    required:
      fileDesignator: string
    properties:
      file:
        type: array
        items: integer

  DisplayNoteMetadataRequest:
    type: object
    required:
      fileDesignator: string
    properties:
      file:
        type: array
        items: integer

  DisplayMusicMetadataResponse:
    type: object
    properties:
      success:
        type: boolean

  DisplayNoteMetadataResponse:
    type: object
    properties:
      success:
        type: boolean